env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
 - prettier
rules:
  prettier/prettier:
    - 2
    - singleQuote: true
      trailingComma: es5
      semi: false
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always