export const supportInfo = {
  languages: [
    {
      linguistLanguageId: 50,
      name: "CSS",
      type: "markup",
      tmScope: "source.css",
      aceMode: "css",
      codemirrorMode: "css",
      codemirrorMimeType: "text/css",
      color: "#563d7c",
      extensions: [".css", ".wxss"],
      parsers: ["css"],
      vscodeLanguageIds: ["css"],
    },
    {
      linguistLanguageId: 262764437,
      name: "PostCSS",
      type: "markup",
      color: "#dc3a0c",
      tmScope: "source.postcss",
      group: "CSS",
      extensions: [".pcss", ".postcss"],
      aceMode: "text",
      parsers: ["css"],
      vscodeLanguageIds: ["postcss"],
    },
    {
      linguistLanguageId: 198,
      name: "Less",
      type: "markup",
      color: "#1d365d",
      aliases: ["less-css"],
      extensions: [".less"],
      tmScope: "source.css.less",
      aceMode: "less",
      codemirrorMode: "css",
      codemirrorMimeType: "text/css",
      parsers: ["less"],
      vscodeLanguageIds: ["less"],
    },
    {
      linguistLanguageId: 329,
      name: "SCSS",
      type: "markup",
      color: "#c6538c",
      tmScope: "source.css.scss",
      aceMode: "scss",
      codemirrorMode: "css",
      codemirrorMimeType: "text/x-scss",
      extensions: [".scss"],
      parsers: ["scss"],
      vscodeLanguageIds: ["scss"],
    },
    {
      linguistLanguageId: 139,
      name: "GraphQL",
      type: "data",
      color: "#e10098",
      extensions: [".graphql", ".gql", ".graphqls"],
      tmScope: "source.graphql",
      aceMode: "text",
      parsers: ["graphql"],
      vscodeLanguageIds: ["graphql"],
    },
    {
      linguistLanguageId: 155,
      name: "Handlebars",
      type: "markup",
      color: "#f7931e",
      aliases: ["hbs", "htmlbars"],
      extensions: [".handlebars", ".hbs"],
      tmScope: "text.html.handlebars",
      aceMode: "handlebars",
      parsers: ["glimmer"],
      vscodeLanguageIds: ["handlebars"],
    },
    {
      linguistLanguageId: 146,
      name: "Angular",
      type: "markup",
      tmScope: "text.html.basic",
      aceMode: "html",
      codemirrorMode: "htmlmixed",
      codemirrorMimeType: "text/html",
      color: "#e34c26",
      aliases: ["xhtml"],
      extensions: [".component.html"],
      parsers: ["angular"],
      vscodeLanguageIds: ["html"],
      filenames: [],
    },
    {
      linguistLanguageId: 146,
      name: "HTML",
      type: "markup",
      tmScope: "text.html.basic",
      aceMode: "html",
      codemirrorMode: "htmlmixed",
      codemirrorMimeType: "text/html",
      color: "#e34c26",
      aliases: ["xhtml"],
      extensions: [
        ".html",
        ".hta",
        ".htm",
        ".html.hl",
        ".inc",
        ".xht",
        ".xhtml",
        ".mjml",
      ],
      parsers: ["html"],
      vscodeLanguageIds: ["html"],
    },
    {
      linguistLanguageId: 146,
      name: "Lightning Web Components",
      type: "markup",
      tmScope: "text.html.basic",
      aceMode: "html",
      codemirrorMode: "htmlmixed",
      codemirrorMimeType: "text/html",
      color: "#e34c26",
      aliases: ["xhtml"],
      extensions: [],
      parsers: ["lwc"],
      vscodeLanguageIds: ["html"],
      filenames: [],
    },
    {
      linguistLanguageId: 391,
      name: "Vue",
      type: "markup",
      color: "#41b883",
      extensions: [".vue"],
      tmScope: "text.html.vue",
      aceMode: "html",
      parsers: ["vue"],
      vscodeLanguageIds: ["vue"],
    },
    {
      linguistLanguageId: 183,
      name: "JavaScript",
      type: "programming",
      tmScope: "source.js",
      aceMode: "javascript",
      codemirrorMode: "javascript",
      codemirrorMimeType: "text/javascript",
      color: "#f1e05a",
      aliases: ["js", "node"],
      extensions: [
        ".js",
        "._js",
        ".bones",
        ".cjs",
        ".es",
        ".es6",
        ".frag",
        ".gs",
        ".jake",
        ".javascript",
        ".jsb",
        ".jscad",
        ".jsfl",
        ".jslib",
        ".jsm",
        ".jspre",
        ".jss",
        ".mjs",
        ".njs",
        ".pac",
        ".sjs",
        ".ssjs",
        ".xsjs",
        ".xsjslib",
        ".wxs",
      ],
      filenames: ["Jakefile"],
      interpreters: [
        "chakra",
        "d8",
        "gjs",
        "js",
        "node",
        "nodejs",
        "qjs",
        "rhino",
        "v8",
        "v8-shell",
        "zx",
      ],
      parsers: [
        "babel",
        "acorn",
        "espree",
        "meriyah",
        "babel-flow",
        "babel-ts",
        "flow",
        "typescript",
      ],
      vscodeLanguageIds: ["javascript", "mongo"],
    },
    {
      linguistLanguageId: 183,
      name: "Flow",
      type: "programming",
      tmScope: "source.js",
      aceMode: "javascript",
      codemirrorMode: "javascript",
      codemirrorMimeType: "text/javascript",
      color: "#f1e05a",
      aliases: [],
      extensions: [".js.flow"],
      filenames: [],
      interpreters: [
        "chakra",
        "d8",
        "gjs",
        "js",
        "node",
        "nodejs",
        "qjs",
        "rhino",
        "v8",
        "v8-shell",
      ],
      parsers: ["flow", "babel-flow"],
      vscodeLanguageIds: ["javascript"],
    },
    {
      linguistLanguageId: 183,
      name: "JSX",
      type: "programming",
      tmScope: "source.js.jsx",
      aceMode: "javascript",
      codemirrorMode: "jsx",
      codemirrorMimeType: "text/jsx",
      extensions: [".jsx"],
      parsers: [
        "babel",
        "babel-flow",
        "babel-ts",
        "flow",
        "typescript",
        "espree",
        "meriyah",
      ],
      vscodeLanguageIds: ["javascriptreact"],
      group: "JavaScript",
    },
    {
      linguistLanguageId: 378,
      name: "TypeScript",
      type: "programming",
      color: "#3178c6",
      aliases: ["ts"],
      interpreters: ["deno", "ts-node"],
      extensions: [".ts", ".cts", ".mts"],
      tmScope: "source.ts",
      aceMode: "typescript",
      codemirrorMode: "javascript",
      codemirrorMimeType: "application/typescript",
      parsers: ["typescript", "babel-ts"],
      vscodeLanguageIds: ["typescript"],
    },
    {
      linguistLanguageId: 94901924,
      name: "TSX",
      type: "programming",
      color: "#3178c6",
      group: "TypeScript",
      extensions: [".tsx"],
      tmScope: "source.tsx",
      aceMode: "javascript",
      codemirrorMode: "jsx",
      codemirrorMimeType: "text/jsx",
      parsers: ["typescript", "babel-ts"],
      vscodeLanguageIds: ["typescriptreact"],
    },
    {
      linguistLanguageId: 174,
      name: "JSON.stringify",
      type: "data",
      color: "#292929",
      tmScope: "source.json",
      aceMode: "json",
      codemirrorMode: "javascript",
      codemirrorMimeType: "application/json",
      aliases: ["geojson", "jsonl", "topojson"],
      extensions: [".importmap"],
      filenames: ["package.json", "package-lock.json", "composer.json"],
      parsers: ["json-stringify"],
      vscodeLanguageIds: ["json"],
    },
    {
      linguistLanguageId: 174,
      name: "JSON",
      type: "data",
      color: "#292929",
      tmScope: "source.json",
      aceMode: "json",
      codemirrorMode: "javascript",
      codemirrorMimeType: "application/json",
      aliases: ["geojson", "jsonl", "topojson"],
      extensions: [
        ".json",
        ".4DForm",
        ".4DProject",
        ".avsc",
        ".geojson",
        ".gltf",
        ".har",
        ".ice",
        ".JSON-tmLanguage",
        ".mcmeta",
        ".tfstate",
        ".tfstate.backup",
        ".topojson",
        ".webapp",
        ".webmanifest",
        ".yy",
        ".yyp",
      ],
      filenames: [
        ".all-contributorsrc",
        ".arcconfig",
        ".auto-changelog",
        ".c8rc",
        ".htmlhintrc",
        ".imgbotconfig",
        ".nycrc",
        ".tern-config",
        ".tern-project",
        ".watchmanconfig",
        "Pipfile.lock",
        "composer.lock",
        "flake.lock",
        "mcmod.info",
        ".babelrc",
        ".jscsrc",
        ".jshintrc",
        ".jslintrc",
        ".swcrc",
      ],
      parsers: ["json"],
      vscodeLanguageIds: ["json"],
    },
    {
      linguistLanguageId: 423,
      name: "JSON with Comments",
      type: "data",
      color: "#292929",
      group: "JSON",
      tmScope: "source.js",
      aceMode: "javascript",
      codemirrorMode: "javascript",
      codemirrorMimeType: "text/javascript",
      aliases: ["jsonc"],
      extensions: [
        ".jsonc",
        ".code-snippets",
        ".code-workspace",
        ".sublime-build",
        ".sublime-commands",
        ".sublime-completions",
        ".sublime-keymap",
        ".sublime-macro",
        ".sublime-menu",
        ".sublime-mousemap",
        ".sublime-project",
        ".sublime-settings",
        ".sublime-theme",
        ".sublime-workspace",
        ".sublime_metrics",
        ".sublime_session",
      ],
      filenames: [],
      parsers: ["jsonc"],
      vscodeLanguageIds: ["jsonc"],
    },
    {
      linguistLanguageId: 175,
      name: "JSON5",
      type: "data",
      color: "#267CB9",
      extensions: [".json5"],
      tmScope: "source.js",
      aceMode: "javascript",
      codemirrorMode: "javascript",
      codemirrorMimeType: "application/json",
      parsers: ["json5"],
      vscodeLanguageIds: ["json5"],
    },
    {
      linguistLanguageId: 222,
      name: "Markdown",
      type: "prose",
      color: "#083fa1",
      aliases: ["md", "pandoc"],
      aceMode: "markdown",
      codemirrorMode: "gfm",
      codemirrorMimeType: "text/x-gfm",
      wrap: true,
      extensions: [
        ".md",
        ".livemd",
        ".markdown",
        ".mdown",
        ".mdwn",
        ".mkd",
        ".mkdn",
        ".mkdown",
        ".ronn",
        ".scd",
        ".workbook",
      ],
      filenames: ["contents.lr", "README"],
      tmScope: "text.md",
      parsers: ["markdown"],
      vscodeLanguageIds: ["markdown"],
    },
    {
      linguistLanguageId: 222,
      name: "MDX",
      type: "prose",
      color: "#083fa1",
      aliases: ["md", "pandoc"],
      aceMode: "markdown",
      codemirrorMode: "gfm",
      codemirrorMimeType: "text/x-gfm",
      wrap: true,
      extensions: [".mdx"],
      filenames: [],
      tmScope: "text.md",
      parsers: ["mdx"],
      vscodeLanguageIds: ["mdx"],
    },
    {
      linguistLanguageId: 407,
      name: "YAML",
      type: "data",
      color: "#cb171e",
      tmScope: "source.yaml",
      aliases: ["yml"],
      extensions: [
        ".yml",
        ".mir",
        ".reek",
        ".rviz",
        ".sublime-syntax",
        ".syntax",
        ".yaml",
        ".yaml-tmlanguage",
        ".yaml.sed",
        ".yml.mysql",
      ],
      filenames: [
        ".clang-format",
        ".clang-tidy",
        ".gemrc",
        "CITATION.cff",
        "glide.lock",
        ".prettierrc",
        ".stylelintrc",
        ".lintstagedrc",
      ],
      aceMode: "yaml",
      codemirrorMode: "yaml",
      codemirrorMimeType: "text/x-yaml",
      parsers: ["yaml"],
      vscodeLanguageIds: ["yaml", "ansible", "home-assistant"],
    },
  ],
};
